---
version: '3.9'
services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "9001:9000"
  mysql-8.0.30:
    image: "mysql:8.0.30"
    container_name: "mysql-server-8.0.30"
    command: --default-authentication-plugin=mysql_native_password --gtid-mode=ON --enforce-gtid-consistency=true --binlog-format=ROW
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
